/* eslint-disable sort-keys */
module.exports = {
  components: {
    categories: [
      {
        name: 'Buttons',
        include: [
          'src/components/Primary-button/Primary-button.js',
          'src/components/Secondary-button/Secondary-button.js',
          'src/components/Tertiary-button/Tertiary-button.js',
          'src/components/Floating-button/Floating-button.js',
          'src/components/Icon-button/Icon-button.js',
          // 'src/components/Card/Card.js',
          // 'src/components/Modal/Modal.js',
          // 'src/components/Table/Table.js',
        ],
      },
      {
        name: 'Form elements',
        include: [
          'src/components/Checkbox/Checkbox.js',
          'src/components/Date-picker/Date-picker.js',
          'src/components/File-input/File-input.js',
          'src/components/Label/Label.js',
          'src/components/Number-input/Number-input.js',
          'src/components/Picker-group/Picker-group.js',
          'src/components/Radio/Radio.js',
          'src/components/Select/Select.js',
          'src/components/Text-input/Text-input.js',
          'src/components/Textarea/Textarea.js',
          'src/components/Time-picker/Time-picker.js',
          'src/components/Toggle-switch/Toggle-switch.js',
        ],
      },
      {
        name: 'General',
        include: [
          'src/components/Alert/Alert.js',
          'src/components/Badge/Badge.js',
          'src/components/Brand/Brand.js',
          // 'src/components/Button/Button.js',
          // 'src/components/Divider/Divider.js',
          // 'src/components/Drawer/Drawer.js',
          // 'src/components/Dropdown/Dropdown.js',
          'src/components/Icon/Icon.js',
          'src/components/Link/Link.js',
          'src/components/Marketing-icon/Marketing-icon.js',
          'src/components/Page-Title/Page-Title.js',
          'src/components/Pagination/Pagination.js',
          'src/components/Popover/Popover.js',
          'src/components/Progress/Progress.js',
          'src/components/Price/Price.js',
          'src/components/Search-input/Search-input.js',
          'src/components/Steps/Steps.js',
          'src/components/Spinner/Spinner.js',
          // 'src/components/Tooltip/Tooltip.js',
          'src/components/StatBase/StatBase.js',
          'src/components/StatCompact/StatCompact.js',
          'src/components/Tabs/Tabs.js',
          'src/components/Text/Text.js',
        ],
      },
    ],
  },
  name: 'Chi design system',
};
