version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: npm install
      - run:
          name: 'Check'
          command: npm run check
      - run:
          name: 'Test'
          command: npm run test
      -run:
          name: 'Push to UXPin Product account'
          command: ./node_modules/@uxpin/merge-cli/bin/uxpin-merge push --token “$UXPIN_TOKEN_UXPIN_PRODUCT_ACCOUNT”
      - run:
          name: 'Push to UXPin'
          command: ./node_modules/@uxpin/merge-cli/bin/uxpin-merge push
