version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: npm install
      - run:
          name: 'Check'
          command: npm run check
      - run:
          name: 'Test'
          command: npm run test
      - run:
          name: 'Push to UXPin if branch is master'
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            then
            npm run push
            npm run push2
            npm run push3    
            else
            echo "On '$CIRCLE_BRANCH' branch - not pushing"
            fi
      - run:
          name: 'Push to UXPin.develop if branch is master'
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            then
            ./node_modules/@uxpin/merge-cli/bin/uxpin-merge push --webpack-config ./webpack.config.js --wrapper ./src/components/UXPinWrapper/UXPinWrapper.js --uxpin-domain develop.uxpin.cloud --token ${UXPIN_AUTH_TOKEN_DEVELOP}
            else
            echo "On '$CIRCLE_BRANCH' branch - not pushing"
            fi
